#define IDD_ABOUT                   500

#define IDD_GRAPH                   530
#define IDB_TOTAL                   535
#define IDB_USED                    536
#define IDB_ALLDIR                  537
#define IDB_1ST                     538
#define IDB_PERCENTON               541
#define IDB_SIZEON                  572
#define IDC_MAXPIES                 573
#define IDP_SETDEF                  542
#define IDP_SETHELP                 543

#define IDD_OPTIONS                 560
#define IDB_BYTES                   532
#define IDB_KBYTES                  533
#define IDB_MBYTES                  534
#define IDP_OPTDEF                  567
#define IDP_OPTHELP                 568

#define IDD_AUTOREF                 580
#define IDC_REFMINUTES              582
#define IDC_THRESFREE               586
#define IDC_THRESSWAP               587
#define IDC_ALARMFREE               588
#define IDC_MESSAGEFREE             589
#define IDC_ALARMSWAP               590
#define IDC_MESSAGESWAP             591
#define IDE_COMMANDFREE             592
#define IDE_COMMANDSWAP             593
#define IDP_NONE                    594
#define IDP_REFHELP                 595

#define IDC_SWAPPIE                 539
#define IDC_SWAPSTAT                544
#define IDC_DIRLIST                 546
#define IDC_LEGEND                  547
#define IDC_EXIT                    548
#define IDC_REFRESH                 549

#define IDD_DIRECTORY               610
#define IDE_DIRECTORY               611

#define IDD_DETAILS                 620
#define IDE_DETDIR                  621
#define IDE_DETLEVEL                622
#define IDE_DETSIZE                 623
#define IDE_DETPERC                 624
#define IDE_DETCUMSIZE              625
#define IDE_DETCUMPERC              626
#define IDE_DETFILES                627
#define IDB_LEFT                    562
#define IDB_RIGHT                   563
#define IDB_DISPLAYNONE             545
#define IDC_ALL                     564

#define IDD_PRINT                   565
#define IDL_PRINT                   566
#define IDP_JOBPROP                 567
#define IDP_HELPPRINT               568
#define IDC_PRINTGRAPH              569

#define IDD_PRINTSTATUS             570
#define IDL_STATUS                  571
#define IDE_PROGRESS                572
